name: Deploy VitePress site to Pages

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Change to VitePress directory
        run: cd blogSSG

      - name: 安装 npm
        uses: actions/setup-node@v3
        with:
          run_install: true
          registry-url: https://registry.npmjs.org/
          version: 18

      # - name: Change to VitePress directory
      #   run: cd blogSSG

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          path: blogSSG
          clear-node-cache: true

      - name: Build with VitePress
        run: |
          npm install
          npm run docs:build
          touch docs/.vitepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
